# Generated by Django 4.2.4 on 2023-10-24 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Day', models.IntegerField(blank=True, null=True)),
                ('DocHasConfirmed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AvailabeForms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=64, null=True)),
                ('Form', models.IntegerField(choices=[(0, 'TABLET_IR'), (1, 'TABLET_SR'), (2, 'SYRUP'), (3, 'SUPPOSITORY'), (4, 'IV'), (5, 'PATCH')], verbose_name='FormType')),
                ('Dosage', models.IntegerField()),
                ('Price', models.IntegerField(blank=True, null=True)),
                ('Unit', models.CharField(max_length=100)),
                ('Quantity', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AvailabeTests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('ReferenceAverage', models.IntegerField()),
                ('ReferenceLow', models.IntegerField()),
                ('ReferenceHigh', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=64)),
                ('Added', models.DateTimeField(auto_now_add=True)),
                ('UserHasGivenPermission', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=60)),
                ('Structure', models.ImageField(blank=True, null=True, upload_to='')),
                ('Description', models.CharField(max_length=512)),
                ('Uses', models.CharField(blank=True, max_length=2048, null=True)),
                ('SideEffects', models.CharField(blank=True, max_length=2048, null=True)),
                ('Mechanism', models.CharField(blank=True, max_length=2048, null=True)),
                ('IsOral', models.BooleanField(default=True)),
                ('IsInjected', models.BooleanField(default=True)),
                ('IsPatch', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=64)),
                ('Location', models.CharField(max_length=512)),
                ('Lat', models.FloatField()),
                ('Lon', models.FloatField()),
                ('Website', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HospitalDoctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.CharField(max_length=64)),
                ('CurrentlyActive', models.BooleanField(default=False)),
                ('Price', models.IntegerField(default=100)),
                ('AllowVirtual', models.BooleanField(default=True)),
                ('SlotLength', models.IntegerField(default=10)),
                ('SatStart', models.TimeField(blank=True, null=True)),
                ('SatEnd', models.TimeField(blank=True, null=True)),
                ('SunStart', models.TimeField(blank=True, null=True)),
                ('SunEnd', models.TimeField(blank=True, null=True)),
                ('MonStart', models.TimeField(blank=True, null=True)),
                ('MonEnd', models.TimeField(blank=True, null=True)),
                ('TueStart', models.TimeField(blank=True, null=True)),
                ('TueEnd', models.TimeField(blank=True, null=True)),
                ('WedStart', models.TimeField(blank=True, null=True)),
                ('WedEnd', models.TimeField(blank=True, null=True)),
                ('ThuStart', models.TimeField(blank=True, null=True)),
                ('ThuEnd', models.TimeField(blank=True, null=True)),
                ('FriStart', models.TimeField(blank=True, null=True)),
                ('FriEnd', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=256, null=True)),
                ('Location', models.CharField(max_length=512)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='images/pharmacies')),
                ('Lat', models.FloatField()),
                ('Lon', models.FloatField()),
                ('Website', models.URLField(blank=True, null=True)),
                ('Address', models.CharField(blank=True, max_length=2048, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestCenters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=128)),
                ('Location', models.CharField(max_length=512)),
                ('Lat', models.FloatField()),
                ('Lon', models.FloatField()),
                ('Website', models.URLField(blank=True, null=True)),
                ('AssociatedHospital', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TestCenter', to='main.hospital')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(blank=True, null=True, upload_to='images/users')),
                ('Name', models.CharField(max_length=64)),
                ('BirthDate', models.DateField()),
                ('Type', models.IntegerField(choices=[(0, 'PATIENT'), (1, 'DOCTOR'), (2, 'PHARMACIST')], verbose_name='User type')),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Visits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PatientVisits', to='main.userprofiles')),
                ('Patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DoctorVisits', to='main.userprofiles')),
            ],
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Value', models.IntegerField(blank=True, null=True)),
                ('Time', models.DateTimeField()),
                ('Status', models.IntegerField(choices=[(0, 'PENDING'), (1, 'COMPLETE')], default=0, verbose_name='TestStatus')),
                ('Device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Results', to='main.devices')),
                ('Patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TestResults', to='main.userprofiles')),
                ('Test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Tests', to='main.availabetests')),
                ('TestCenter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Results', to='main.testcenters')),
            ],
        ),
        migrations.CreateModel(
            name='TestCenterTests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pricing', models.IntegerField(blank=True, null=True)),
                ('Description', models.CharField(max_length=256)),
                ('Test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TestCenters', to='main.availabetests')),
                ('TestCenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Tests', to='main.testcenters')),
            ],
        ),
        migrations.CreateModel(
            name='RecommendTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AutoForwardResults', models.BooleanField(default=True)),
                ('Appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RecommmededTests', to='main.appointment')),
                ('Test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RecommendedBy', to='main.availabetests')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AllowSubstitutiions', models.BooleanField(default=True)),
                ('Lenght', models.IntegerField()),
                ('Quantity', models.IntegerField()),
                ('Instructions', models.CharField(max_length=2048)),
                ('Doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Prescriptions', to='main.appointment')),
                ('Drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Prescriptions', to='main.availabeforms')),
            ],
        ),
        migrations.CreateModel(
            name='PharmacyInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Price', models.IntegerField(blank=True, null=True)),
                ('Quantity', models.IntegerField(blank=True, null=True)),
                ('Drug', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.availabeforms')),
                ('Pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.pharmacy')),
            ],
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='Pharmacist',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Pharmacy', to='main.userprofiles'),
        ),
        migrations.CreateModel(
            name='HospitalDoctorTiming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StartTime', models.TimeField()),
                ('EndTime', models.TimeField()),
                ('WeekDayCode', models.IntegerField(default=0)),
                ('Form', models.IntegerField(choices=[(0, 'TABLET_IR'), (1, 'TABLET_SR'), (2, 'SYRUP')], verbose_name='VisitTimeType')),
                ('HospitalDoctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Timings', to='main.hospitaldoctors')),
            ],
        ),
        migrations.AddField(
            model_name='hospitaldoctors',
            name='Doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Hospitals', to='main.userprofiles'),
        ),
        migrations.AddField(
            model_name='hospitaldoctors',
            name='Hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Doctors', to='main.hospital'),
        ),
        migrations.CreateModel(
            name='DrugBrands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(blank=True, null=True, upload_to='images/brands')),
                ('Name', models.CharField(max_length=120)),
                ('Manafacturer', models.CharField(max_length=128)),
                ('Price', models.IntegerField(blank=True, null=True)),
                ('GenericDrug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Brands', to='main.drug')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Speciality', models.CharField(blank=True, max_length=128, null=True)),
                ('Quals', models.CharField(blank=True, max_length=128, null=True)),
                ('Rating', models.IntegerField(blank=True, null=True)),
                ('Ratings', models.IntegerField(blank=True, null=True)),
                ('Experience', models.IntegerField(default=0)),
                ('Doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='MetaInfo', to='main.userprofiles')),
            ],
        ),
        migrations.AddField(
            model_name='devices',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Devices', to='main.userprofiles'),
        ),
        migrations.CreateModel(
            name='DevicePermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Granted', models.BooleanField(default=False)),
                ('Device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Permissions', to='main.devices')),
                ('Test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DevicesAuthorized', to='main.availabetests')),
            ],
        ),
        migrations.AddField(
            model_name='availabeforms',
            name='Brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Forms', to='main.drugbrands'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='Doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.hospitaldoctors'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='Patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.userprofiles'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='Timing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Appointments', to='main.hospitaldoctortiming'),
        ),
    ]
