# Generated by Django 4.2.4 on 2023-10-24 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_pharmacy_pharmacist'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='Pharmacist',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Pharmacy', to='main.userprofiles'),
        ),
    ]
